Repository UnicornGlobal/quick-dash-framework, pull requests merged in 2019-11, with the labels that each got.

#237 Version bump to 2.3.7
  package-lock.json
  package.json
Labels: 🔍 Ready for Review

#236 Fix duplicate navigation issue
  package.json
  src/auth/index.js
Labels: size/M, 🔍 Ready for Review

#238 User Profile Menu
  package-lock.json
  package.json
  src/components/Containers/PageContainer.vue
  src/components/SideBar/SideBar.vue
  src/components/SideBar/SideBarMenuItem.vue
  src/components/SideBar/UserProfile.vue
  src/components/TopNav/TopNav.vue
  src/components/TopNav/UserMenu.vue
  src/config/admin.js
  src/config/sidebar.js
  src/config/usermenu.js
  src/router/admin.js
  src/router/index.js
  test/unit/specs/App.spec.js
  test/unit/specs/auth/index.spec.js
  test/unit/specs/components/SideBar/SideBar.spec.js
  test/unit/specs/components/TopNav/UserMenu.spec.js
  test/unit/specs/pages/Admin/Home/Home.spec.js
  test/unit/specs/pages/PasswordResetForm.spec.js
  test/unit/specs/pages/PasswordResetRequest.spec.js
  test/unit/specs/pages/User/Details.spec.js
  test/unit/specs/pages/User/Home/Home.spec.js
Labels: size/XL, 🔍 Ready for Review
