Repository UnicornGlobal/quick-dash-framework, pull requests merged in 2019-12, with the labels that each got.

#240 Widget
  src/components/SideBar/SideBar.vue
  src/config/sidebar.js
  test/unit/specs/components/SideBar/SideBar.spec.js
Labels: size/M, 🔍 Ready for Review

#241 Widget Tweaks
  package.json
  src/App.vue
  src/assets/sass/base.scss
  src/components/Cards/VerifyAccountCard.vue
  src/components/ChangeProfilePicture.vue
  src/components/Containers/PageContainer.vue
  src/components/Containers/PageSection.vue
  src/components/SideBar/SideBar.vue
  src/config/index.js
  src/pages/Login.vue
  src/pages/User/EditDetails.vue
  test/unit/specs/App.spec.js
  test/unit/specs/components/Alert.spec.js
  test/unit/specs/components/Cards/VerifyAccountCard.spec.js
  test/unit/specs/components/Containers/PageContainer.spec.js
  test/unit/specs/components/Prompt.spec.js
  test/unit/specs/components/SideBar/SideBar.spec.js
Labels: size/L, 🔍 Ready for Review

#242 Widget
  package-lock.json
  package.json
  src/App.vue
  src/assets/sass/base.scss
  src/components/Cards/VerifyAccountCard.vue
  src/components/ChangeProfilePicture.vue
  src/components/Containers/PageContainer.vue
  src/components/Containers/PageSection.vue
  src/components/SideBar/SideBar.vue
  src/config/index.js
  src/config/sidebar.js
  src/pages/Login.vue
  src/pages/User/EditDetails.vue
  test/unit/specs/App.spec.js
  test/unit/specs/components/Alert.spec.js
  test/unit/specs/components/Cards/VerifyAccountCard.spec.js
  test/unit/specs/components/Containers/PageContainer.spec.js
  test/unit/specs/components/Prompt.spec.js
  test/unit/specs/components/SideBar/SideBar.spec.js
Labels: size/L, 🔍 Ready for Review

#243 Confirm Login
  package-lock.json
  package.json
  src/App.vue
  src/api/auth.js
  src/api/user.js
  src/assets/sass/base.scss
  src/auth/index.js
  src/components/Cards/VerifyAccountCard.vue
  src/components/Containers/PageSection.vue
  src/components/Form/FormGroup.vue
  src/components/Modal.vue
  src/config/signup.js
  src/pages/Admin/Users/Index.vue
  src/pages/Admin/Users/UserDetails.vue
  src/pages/Confirm.vue
  src/pages/Login.vue
  src/pages/PasswordResetForm.vue
  src/router/auth.js
  test/unit/specs/api/auth.spec.js
  test/unit/specs/api/users.spec.js
  test/unit/specs/components/SideBar/SideBar.spec.js
  test/unit/specs/pages/Login.spec.js
  test/unit/specs/pages/PasswordResetForm.spec.js
Labels: size/L, 🔍 Ready for Review

#244 Support "any role" routes
  README.md
  package.json
  src/router/index.js
Labels: size/S, 🔍 Ready for Review

#245 Rework user role process
  package.json
  src/components/Form/Checkbox.vue
  src/components/Modal.vue
  src/components/Prompt.vue
  src/pages/Admin/Users/AssignRoleForm.vue
  src/pages/Admin/Users/Index.vue
  src/pages/Admin/Users/UserDetails.vue
  test/unit/specs/api/users.spec.js
  test/unit/specs/components/Alert.spec.js
  test/unit/specs/components/Prompt.spec.js
  test/unit/specs/pages/Admin/Users/AssignRoleForm.spec.js
Labels: size/L, 🔍 Ready for Review

#246 Better Uploader
  package-lock.json
  package.json
  src/components/ChangeProfilePicture.vue
  src/components/Modal.vue
  src/components/SideBar/SideBarMenuItem.vue
  src/config/sidebar.js
  src/lib/validation.js
Labels: size/S, 🔍 Ready for Review

#247 No delay when clicking logout
  package.json
  src/App.vue
  src/components/SideBar/SideBarMenuItem.vue
  src/components/TopNav/UserMenu.vue
Labels: size/XS, 🔍 Ready for Review
