Repository UnicornGlobal/quick-dash-framework, pull requests merged in 2019-10, with the labels that each got.

#225 Update Dependency
  package-lock.json
  package.json
Labels: size/XS, 🔍 Ready for Review

#226 refactor top bar component to use slots
  package-lock.json
  package.json
  src/App.vue
  src/components/Containers/PageContainer.vue
  src/components/Containers/PageSection.vue
  src/components/TopNav/TopNav.vue
Labels: size/XL, ✅ Approved

#227 Rework the Password Reset Mechanism
  package-lock.json
  package.json
  src/api/user.js
  src/auth/index.js
  src/components/SideBar/SideBar.vue
  src/components/TopNav/UserMenu.vue
  src/helpers/utils.js
  src/pages/Admin/Users/Index.vue
  src/pages/Login.vue
  src/pages/PasswordResetForm.vue
  src/pages/PasswordResetRequest.vue
  src/router/auth.js
  test/unit/specs/pages/Login.spec.js
  test/unit/specs/pages/PasswordReset.spec.js
  test/unit/specs/router/index.spec.js
Labels: size/L, 🔍 Ready for Review

#229 Sidebar Fixes
  package-lock.json
  package.json
  src/App.vue
  src/components/ChangeProfilePicture.vue
  src/components/Containers/PageContainer.vue
Labels: size/S, 🔍 Ready for Review

#230 Layout Fixes
  package.json
  src/App.vue
  src/components/ChangeProfilePicture.vue
  src/components/Containers/PageContainer.vue
  src/components/TopNav/UserMenu.vue
Labels: size/M, 🔍 Ready for Review

#231 Version bump
  package.json
Labels: size/XS

#232 Signup Changes
  package-lock.json
  package.json
  src/assets/sass/_forms.scss
  src/config/signup.js
Labels: size/S, 🔍 Ready for Review

#233 Max width on modals
  package.json
  src/components/Modal.vue
  src/http/index.js
Labels: size/XS, 🔍 Ready for Review

#235 v2.3.6
  package-lock.json
  package.json
Labels: size/XS, 🔍 Ready for Review
